version: '2'
services:
  db:
    build: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=docker
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - /tmp/home/user/database:/var/lib/postgresql
  db_exporter:
    image: bitnami/postgres-exporter
    depends_on:
      - db
    restart: always
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:$POSTGRES_PASSWORD@db:5432/postgres?sslmode=disable
    ports:
      - "0.0.0.0:9187:9187"
  front:
    build: front
    depends_on:
      - api
    restart: always
    ports:
      - "0.0.0.0:8080:80"
  api:
    build: .
    depends_on:
      - db
    restart: always
    environment:
      - APP_DB_HOST=db
      - APP_DB_PORT=5432
      - APP_DB_USERNAME=postgres
      - APP_DB_PASSWORD=$POSTGRES_PASSWORD
      - APP_DB_NAME=docker
      - APP_BASE_URL=https://llil.gq
    ports:
      - "0.0.0.0:8888:8888"
